name: Notion Cron

on:
    schedule:
        - cron: "0 16 * * *" # Midnight Malaysia time (UTC+8 → 16:00 UTC)
    workflow_dispatch:

jobs:
    run-cron:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2

            - name: Install dependencies
              run: bun install --frozen-lockfile

            - name: Run script
              run: bun run index.ts
              env:
                  NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
                  NOTION_DATA_SOURCE_ID: ${{ secrets.NOTION_DATA_SOURCE_ID }}
